name: Daily Scraper

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  
env:
  ACTIONS_STEP_DEBUG: true

jobs:
  scrape:
    runs-on: 'ubuntu-latest'


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Install Firefox and GeckoDriver
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y firefox
      #     wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
      #     tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
      #     chmod +x geckodriver
      #     sudo mv geckodriver /usr/local/bin/
      # - name: Move Snap Firefox to /usr/bin
      #   run: |
      #     sudo cp /snap/bin/firefox /usr/bin/firefox
      #     sudo chmod +x /usr/bin/firefox
      #     ls -l /usr/bin/firefox
      # - name: Prioritize /usr/bin in PATH
      #   run: |
      #     export PATH="/usr/bin:$PATH"
      #     echo "export PATH=/usr/bin:$PATH" >> $GITHUB_ENV
      # - name: Debug Firefox and GeckoDriver
      #   run: |
      #     firefox --version
      #     which firefox
      #     which geckodriver
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run scraper
        run: python scrape_current_nba_games.py
        env:
          SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      - name: Upload Screenshot
        if: always()  # Always upload the artifact even if the scraper fails
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshot.png